select * from USERS 
  LEFT JOIN ANSWERS on ANSWERS.USER_ID = USERS.ID
  LEFT JOIN REPORTS on REPORTS.QUESTION_ID = ANSWERS.QUESTION_ID

  where ANSWERS.QUESTION_ID in 
  (select Q_ID as "Q_ID" from (select QUESTIONS.ID as "Q_ID" FROM USERS 
       RIGHT JOIN QUESTIONS 
       ON USERS.ID = QUESTIONS.USER_ID 
      WHERE USERS.USERNAME like '&username' ORDER BY QUESTIONS.CREATED_AT)
      where rownum = &num)
;